Fix Continuous Integration (#90)
* Don't use versions of plone.app.robotframework.

* Separates versions of Plone 4.3 and Plone 5.1

* Pinn configparser = 3.5.3.

Avoid:

Error: There is a version conflict.
We already have: UNKNOWN 0.0.0
but flake8 3.3.0 requires 'configparser'.

* Add ``cssselect`` as pakage dependency.

cssselect is an extra of lxml.

* Extends versions of cover in versuions-4.3.cfg